### ISSUE TITLE
ID as string ?

### ISSUE THREAD

**Issue by waghanza** [woohoolabs/yin#75] opened 2018-10-24 15:33 UTC
Hi @kocsismate,

Database `id` are considered as string, for example in `hasIncludedResource`.
https://github.com/woohoolabs/yin/blob/65e6bc15aa6efdcef8c17a4b246ba581192f5b7b/src/JsonApi/Schema/Data/AbstractData.php#L43

Should not `id` be considered as  `int` ?

Regards,

**Comment by kocsismate** [comment] 2018-10-24 17:58
Hey @waghanza!

Legit question, but long story short: it is by the specification. https://jsonapi.org/format/#document-resource-object-identification. To be honest, I was also surprised when I discovered this rule.

I am closing the ticket. Have a nice evening! :)

**Closed as completed by kocsismate** 2018-10-24 17:58 UTC

**Comment by waghanza** [comment] 2018-10-25 08:17
@kocsismate I can unserstand with https://github.com/json-api/json-api/issues/1312 that `id` can also be a `string` (in **specs**)

but are users of **yin** using anything else that `integer` ?

probably, in this case not respecting strictly jsonapi specs is legit

what do you think ?

**Comment by waghanza** [comment] 2018-10-25 12:20
@kocsismate an other case is filtering, as of `jsonapi` specify how filtering **should** work 
https://jsonapi.org/recommendations/#filtering

for example, when trying to filler using `/cars?filter[id]=13`, we have then an `int` in `$attributes` in `transformAttributes`, then we have **Function name must be a string** in line `126`

**Comment by kocsismate** [comment] 2018-10-25 20:46
@waghanza, I don't think that everyone is using `int`: for example I use `UUID`s as IDs. But I get your point, the method in question could have the `hasIncludedResource(string $type, $id)` signature. The problem with this is that I love type declarations, so I wouldn't really like to omit the type of the second parameter unless it is extremely annoying.

Regarding your last comment, I still don't know how you could get `Function name must be a string` error... And how filtering is related to attributes? Please describe exactly what is going on in your application, because I'm curious what the problem is.
